# Generated by Django 2.1.7 on 2019-03-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('ignore', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned', models.BooleanField(default=False, help_text='Has this resource had its links/words scanned?')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('blurb', models.TextField()),
                ('badges', models.ManyToManyField(related_name='pages', to='search.Badge')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Domain')),
                ('links_to', models.ManyToManyField(related_name='links_from', to='search.Page')),
                ('links_to_domains', models.ManyToManyField(related_name='links_from', to='search.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('occurances', models.IntegerField(default=0)),
                ('title_occurances', models.IntegerField(default=0)),
                ('header_occurances', models.IntegerField(default=0)),
                ('is_stop_word', models.BooleanField(default=False)),
                ('nexts', models.ManyToManyField(related_name='prevs', to='search.Word')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='words',
            field=models.ManyToManyField(related_name='pages', to='search.Word'),
        ),
    ]
