# Generated by Django 2.1.7 on 2019-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190325_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='badges',
            field=models.ManyToManyField(related_name='results', to='search.Badge'),
        ),
        migrations.AlterField(
            model_name='result',
            name='words',
            field=models.ManyToManyField(related_name='results', to='search.Word'),
        ),
    ]
