# Generated by Django 2.1.7 on 2019-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190326_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='arxiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='hackernews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='semanticscholar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='uw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='wiki',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='result',
            name='badges',
        ),
        migrations.AddField(
            model_name='result',
            name='badges',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
