# Generated by Django 2.1.7 on 2019-03-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190326_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='badges',
        ),
        migrations.AddField(
            model_name='result',
            name='duckduckgo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='blurb',
            field=models.TextField(default='No blurb'),
        ),
    ]
