# Generated by Django 2.1.7 on 2019-03-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20190329_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='occurances',
        ),
        migrations.AddField(
            model_name='query',
            name='is_academic',
            field=models.BooleanField(default=False, help_text='Is this an academic topic? - Moves wikipedia articles to the top'),
        ),
        migrations.AddField(
            model_name='query',
            name='is_news_topic',
            field=models.BooleanField(default=False, help_text='Is this a news topic? - Moves news topics to the top'),
        ),
        migrations.AddField(
            model_name='query',
            name='is_scholarly',
            field=models.BooleanField(default=False, help_text='Is this a scholarly topic? - Shoves more arxiv articles into search result'),
        ),
    ]
