# Generated by Django 2.1.7 on 2019-03-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20190329_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_cs',
            field=models.BooleanField(default=False, help_text='Is this a computer science topic? - Moves CS material to the top'),
        ),
        migrations.AddField(
            model_name='query',
            name='is_programming',
            field=models.BooleanField(default=False, help_text='Is this a programming topic? - Moves stackoverflow questions to the top'),
        ),
    ]
