# Generated by Django 2.1.7 on 2019-03-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20190329_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('nexts', models.ManyToManyField(related_name='prevs', to='search.Word')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='results',
            field=models.ManyToManyField(related_name='words', to='search.Result'),
        ),
    ]
