# Generated by Django 2.1.7 on 2019-04-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_result_stopword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='stopword',
        ),
        migrations.AddField(
            model_name='word',
            name='stopword',
            field=models.BooleanField(default=False),
        ),
    ]
