# Generated by Django 2.1.7 on 2019-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_auto_20190401_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='stopword',
        ),
        migrations.AddField(
            model_name='query',
            name='stopword',
            field=models.BooleanField(default=False),
        ),
    ]
